# Generated by Django 2.1.15 on 2020-12-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('designation', models.CharField(max_length=60)),
                ('district', models.CharField(blank=True, max_length=60, null=True)),
                ('profile_link_tw', models.URLField(blank=True, null=True)),
                ('profile_link_fac', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profilepics')),
                ('is_featured_member', models.BooleanField()),
                ('is_home_featured_member', models.BooleanField()),
            ],
        ),
    ]
