# Generated by Django 2.1.15 on 2020-12-08 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('images', models.ImageField(blank=True, upload_to='profilepics')),
                ('is_featured_member', models.BooleanField()),
                ('is_home_featured_member', models.BooleanField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
