# Generated by Django 2.1.15 on 2020-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
